CHANGELOG.md
avromatic.gemspec
lib/avromatic/model/raw_serialization.rb
lib/avromatic/version.rb
spec/avromatic/model/messaging_serialization_spec.rb

New tests verify that models of these forms can be initialized using a hash, and round-trip correctly through serialization.

Fix serialization of array or map of nested models

---

CHANGELOG.md
lib/avromatic/model/attributes.rb
lib/avromatic/version.rb
spec/avro/dsl/test/real_union.rb
spec/avro/dsl/test/value.rb
spec/avro/schema/test/real_union.avsc
spec/avromatic/model/builder_spec.rb

This change adds test cases and a more descriptive error when the top-level type used to define a model is not an Avro record.
This provides better feedback for the schema in Issue #16.

Raise an error for non-record Avro types

---

Appraisals
CHANGELOG.md
avromatic.gemspec
gemfiles/avro_salsify_fork.gemfile
lib/avromatic/model.rb
lib/avromatic/model/attributes.rb
lib/avromatic/model/logical_types.rb
lib/avromatic/version.rb
spec/avro/dsl/test/logical_types.rb
spec/avro/schema/test/logical_types.avsc
spec/avromatic/model/builder_spec.rb
spec/avromatic/model/messaging_serialization_spec.rb
spec/avromatic/model/raw_serialization_spec.rb
spec/spec_helper.rb
spec/support/contexts/logical_types_serialization.rb
spec/support/helpers/logical_types_helper.rb

The changes here to support the three logical types that make sense with builtin Ruby types were relatively straightforward. But the actual use of these logical types found some issues with the proposed changes to the official avro gem: https://github.com/apache/avro/pull/116. This required a new release of our fork.

Add support for logical types

---

CHANGELOG.md
lib/avromatic/model/attribute/record.rb
lib/avromatic/model/attributes.rb
lib/avromatic/model/builder.rb
lib/avromatic/model/raw_serialization.rb
lib/avromatic/version.rb
spec/avromatic/model/builder_spec.rb
spec/avromatic/model/raw_serialization_spec.rb

There are two basic issues addressed here:
- the serialization of arrays/maps of unions
- the coercion of records within other complex types
The latter issue seems to be a problem with Virtus. An array of generated models is coerced correctly, but an array of arrays of generated models is not coerced (for example). 
To workaround this issue a similar solution to that used for union support was implemented. Each generated model is registered with axiom and there is a new `Virtus::Attribute`subclass that ensures generated models are coerced by checking for a model instance or creating and validating a new one.
The plan once again is to create a pre-release with these changes for further testing.

Fix the handling of nested, complex types

---

.rspec
.rubocop.yml
CHANGELOG.md
README.md
lib/avromatic.rb
lib/avromatic/model/attributes.rb
lib/avromatic/model/builder.rb
lib/avromatic/model/configurable.rb
lib/avromatic/model/configuration.rb
lib/avromatic/model/nested_models.rb
lib/avromatic/model/value_object.rb
lib/avromatic/model_registry.rb
lib/avromatic/version.rb
spec/avromatic/model/builder_nested_models_spec.rb
spec/avromatic/model/builder_spec.rb
spec/avromatic/model_registry_spec.rb
spec/spec_helper.rb

Nested models are stored in a `ModelRegistry` (`Avromatic.nested_models`). This registry is inherited by generated models, but can also be overridden. Models in the registry can be retrieved by schema full name, optionally with a namespace prefix removed.
Also, added README info on experimental union support.

Reuse nested models

---

CHANGELOG.md
lib/avromatic/model/attributes.rb
lib/avromatic/model/nested_models.rb
lib/avromatic/model_registry.rb
lib/avromatic/version.rb
spec/avro/dsl/test/recursive.rb
spec/avro/schema/test/recursive.avsc
spec/avromatic/model/builder_spec.rb
spec/avromatic/model_registry_spec.rb

Any model that can be used as a nested model (i.e. it only has a value schema) is now automatically registered before building attributes.
This change also fixes a bug looking up previously registered models and an issue registering models that do not match a prefix.

Support recursive models

---

lib/avromatic/model/nested_models.rb
lib/avromatic/version.rb
spec/avromatic/model/raw_serialization_spec.rb

Models that can be nested are now automatically added to the model registry when they are built. This fix moves the registration with `Axiom::Types` to the same place. Without this fix, a model could be built and registered with Avromatic without being recognized by Axiom.

Nested models Axiom::Types fix

---

CHANGELOG.md
avromatic.gemspec
lib/avromatic/model/attributes.rb
lib/avromatic/version.rb
spec/avromatic/model/builder_spec.rb
spec/avromatic/model/builder_validation_spec.rb

Previously a presence check was used for all required fields. This check uses `blank?` which has the effect of marking empty arrays and maps as invalid.
As part of this change, the validation specs were moved into a separate file.

Allow empty required array and map fields

---

CHANGELOG.md
lib/avromatic/model/attributes.rb
spec/avromatic/model/builder_validation_spec.rb

This change makes incremental progress on validation. Nested models are validated but only if the nested model is used directly as the type for a field. Nested models embedded within complex types will be handled separately.

Validate nested models

---

lib/avromatic/model_registry.rb
lib/avromatic/version.rb
spec/avromatic/model_registry_spec.rb

This change only allows a model's full name to be registered once for the same registry. Any attempt to register the same name again raises an error.

Only allow nested models to be registered once

---

CHANGELOG.md
avromatic.gemspec
lib/avromatic/model/attributes.rb
lib/avromatic/model/builder.rb
lib/avromatic/model/validation.rb
lib/avromatic/version.rb
spec/avromatic/model/builder_validation_spec.rb

This change completes validation for all of the places where nested models can appear. 
Instead of attempting to predict (based on the schema) where nested, complex types will occur, this implementation checks any complex types recursively.

Nested validation of records embedded in complex types

---

.rubocop.yml
CHANGELOG.md
lib/avromatic/model/attribute/abstract_timestamp.rb
lib/avromatic/model/attribute/timestamp_micros.rb
lib/avromatic/model/attribute/timestamp_millis.rb
lib/avromatic/model/logical_types.rb
spec/spec_helper.rb
spec/support/contexts/logical_types_serialization.rb

With this change, instances match exactly after a round-trip through serialization and deserialization.
Previously a timestamp stored in a model could have greater precision than a value returned after deserialization.
This removes any need to truncate timestamps before assigning to an Avromatic model.

Coerce timestamps to the supported precision

---

CHANGELOG.md
README.md
lib/avromatic.rb
lib/avromatic/model/attributes.rb
lib/avromatic/model_registry.rb
lib/avromatic/version.rb
spec/avromatic/model_registry_spec.rb
spec/avromatic_spec.rb
spec/spec_helper.rb

This change replaces the `Avromatic.on_initialize` proc with an `Avromatic.preregister_models` array that can be used to specify an array of models that are registered at the end of `.configure` and on code reloading for Rails applications.
The previous approach relied on the side-effect of a model being registered when it is defined. This was problematic for the first call to the `to_prepare` block for a Rails application because the registry would be cleared, but the constants were still defined for the models, so they would not be re-add simply by referencing. 
I considered disabling the first call to the `to_prepare` block, or disabling the clearing of the registry for the first call to the `to_prepare` block. But being explicit about registering these models seemed cleaner. The …

New approach for extended model that must be loaded first

---

CHANGELOG.md
lib/avromatic.rb
lib/avromatic/railtie.rb
lib/avromatic/version.rb
spec/avromatic_spec.rb

This change is part of how I originally considered fixing the initialization issues with Rails. Since no code reloading happens between initialize and the first call to `to_prepare` do not clear the nested models registry on the first call.

Fix Rails initialization again

---

CHANGELOG.md
lib/avromatic/model/type_registry.rb
lib/avromatic/version.rb
spec/avromatic/model/builder_spec.rb

The "class" that is used for Virtus attributes is not always a Class. For arrays and maps it will be an instance of an Array or Hash. This change avoids performing undefined checks on those values.

Fix for optional array and map fields

---

CHANGELOG.md
lib/avromatic.rb
lib/avromatic/version.rb
spec/avromatic_spec.rb

Clear the schema store used by Avromatic if the implementation supports it.

Clear schema store before code reloading

---

CHANGELOG.md
lib/avromatic/model/message_decoder.rb
lib/avromatic/rspec.rb
lib/avromatic/schema_registry_patch.rb
lib/avromatic/test/fake_schema_registry_server.rb
lib/avromatic/version.rb
spec/avromatic/schema_registry_patch_spec.rb

This change adds patch for `AvroTurf::SchemaRegistry` and `FakeSchemaRegistryServer` (both from `AvroTurf`) to support the `GET /subjects/:subject/fingerprints/:fingerprint` endpoint that is used to lookup schemas prior to registering.
Patching these classes seemed like the least intrusive way to add this support. By modifying the `SchemaRegistry` client, the `Messaging` API does not need to be touched.
All of our applications that use Avro use this gem, so they will automatically pick up this additional functionality, and tests use the fake server via `avromatic/rspec` which is updated here to pull in the patched version.
Prime: @will89

Add support for looking up schema by fingerprint before registering

---

CHANGELOG.md
README.md
lib/avromatic/schema_registry_patch.rb
lib/avromatic/version.rb
spec/avromatic/schema_registry_patch_spec.rb

I thought it made sense to support the additional endpoint directly in the `SchemaRegistry` client, so this change moves things around in the patch to expose it.

Refactor to expose AvroTurf::SchemaRegistry#lookup_subject_schema

---

CHANGELOG.md
README.md
lib/avromatic/messaging.rb
lib/avromatic/model/messaging_serialization.rb
lib/avromatic/version.rb
spec/avromatic/model/messaging_serialization_spec.rb

This method provides a convenient way to register the schemas associated with a model without needing to publish a message.
Eventually, this could be surrounded by calls that alter the compatibility level for a subject in the schema registry, if necessary. Currently the schema registry client doesn't support the Config API so I'm adding this by itself for now.

Add register_schemas! method to generated models

---

CHANGELOG.md
lib/avromatic/rspec.rb
lib/avromatic/version.rb

After releasing this I found one more reference to the old name that I missed.

Replace another reference to fake_schema_registry_server

---

CHANGELOG.md
lib/avromatic/io/datum_reader.rb
lib/avromatic/model/attributes.rb
spec/avro/dsl/test/null_in_union.rb
spec/avro/dsl/test/optional_union.rb
spec/avro/schema/test/null_in_union.avsc
spec/avro/schema/test/optional_union.avsc
spec/avromatic/io/datum_reader_spec.rb
spec/avromatic/model/builder_spec.rb

This fixes the issue that we saw with optional union decoding including the index of the null type.
In the process of adding some test coverage around this I found another problematic case around null as a union member. That one is harder to fix, and not something that I'd expect us to do. For now I've marked the specs as pending for that case, and added an exception when we detect the situation.
Prime: @will89

Fix optional union decoding

---

CHANGELOG.md
lib/avromatic/model/raw_serialization.rb
lib/avromatic/version.rb
spec/avromatic/io/datum_reader_spec.rb
spec/avromatic/model/raw_serialization_spec.rb

There have been a couple of cases where it would have been useful for apps to have access to this private method. Its `#value_attributes_for_avro` sibling was already public. Also, increase test coverage since this is being exposed.

Expose the key_attributes_for_avro method on models

---

CHANGELOG.md
lib/avromatic/model/raw_serialization.rb
lib/avromatic/version.rb
spec/avromatic/model/raw_serialization_spec.rb

I added public methods to Avromatic model instances to return the equivalent of `#value_attributes_for_avro` but excluding the custom values for union member index and encoding provider. 
I went with the term `datum` as it appears throughout the Avro gem source for the data to be encoded using Avro.
The tests are based on the examples for `#value_attributes_for_avro` but demonstrate the difference of what the new methods return.
The implementation is via the passing of a `:strict` flag indicating that result should strictly conform to Avro specification.
Prime: @jkapell
Fixes #77

Add #avro_value_datum and #avro_key_datum

---

CHANGELOG.md
README.md
lib/avromatic/rspec.rb
lib/avromatic/version.rb
spec/spec_helper.rb

The RSpec support in `avromatic/rspec` does not actually work unless it is paired with calling `Avromatic.build_messaging!` also before each example.
It makes sense to also include this in the support file. 
Also, added a section to the README describing the RSpec support.
Prime: @jturkel 
CC: @zoso10

Add build_messaging! to avromatic/rspec

---

.travis.yml
Appraisals
gemfiles/avro_patches_5_0.gemfile
gemfiles/avro_patches_5_1.gemfile
gemfiles/rails5_0.gemfile
gemfiles/rails5_1.gemfile

This adds testing against Ruby 2.5.0 to the Travis configuration (no issues found), and bumps the patch versions for Ruby and Rails.

Test against Ruby 2.5 and bump patch versions

---

CHANGELOG.md
lib/avromatic/model/message_decoder.rb
lib/avromatic/version.rb
spec/avromatic/model/message_decoder_spec.rb

We have a use case where we want to dispatch only on the model associated with a message without performing a full decode.
This change exposes a method to return just the model based on a message key and value.

Add MessageDecoder method to return model only

---

CHANGELOG.md
lib/avromatic/model/allowed_type_validator.rb
lib/avromatic/model/attribute/record.rb
lib/avromatic/model/attribute/union.rb
lib/avromatic/model/attributes.rb
lib/avromatic/version.rb
spec/avromatic/model/builder_spec.rb
spec/avromatic/model/builder_validation_spec.rb

This change improves assignment to subrecords using a hash. Previously, if the resulting subrecord was invalid, it would be set to nil. This change allows the subrecord to be partially assigned which improves validation and error handling because we then know exactly which fields are missing.
This change does not apply to records in unions. Improves could be made there in the future to find the "best" match among invalid values, but for now records in unions remain unassigned if they are invalid.
One quirk of Virtus that is also addressed here is that it will assign an invalid value to a primitive type, if if it is unable to coerce the value. 
Members of a union are now required to be the correct type after a coercion. E.g. previously an invalid hash for a record in a union could be …

Improve record assignment from a hash

---

CHANGELOG.md
lib/avromatic/version.rb

This is just a version bump to 1.0.0 in preparation for landing the compatibility breaking Virtus replacement (i.e. #89 and friends) in 2.0.

Release 1.0.0

---

CHANGELOG.md
README.md
lib/avromatic.rb
lib/avromatic/model/attributes.rb
spec/avromatic/io/datum_writer_spec.rb
spec/avromatic/model/builder_spec.rb

This raises an exception if a model instance is constructed with unknown attributes. This behavior can be disabled by setting `Avromatic.allow_unknown_attributes = false`. It's already uncovered some bugs in the Salsify codebase :)

Prevent model instances from being constructed with unknown attributes

---

lib/avromatic/model/attributes.rb
lib/avromatic/model/types/abstract_timestamp_type.rb
lib/avromatic/model/types/array_type.rb
lib/avromatic/model/types/boolean_type.rb
lib/avromatic/model/types/custom_type.rb
lib/avromatic/model/types/date_type.rb
lib/avromatic/model/types/enum_type.rb
lib/avromatic/model/types/fixed_type.rb
lib/avromatic/model/types/float_type.rb
lib/avromatic/model/types/integer_type.rb
lib/avromatic/model/types/map_type.rb
lib/avromatic/model/types/null_type.rb
lib/avromatic/model/types/record_type.rb
lib/avromatic/model/types/string_type.rb
lib/avromatic/model/types/timestamp_micros_type.rb
lib/avromatic/model/types/timestamp_millis_type.rb
lib/avromatic/model/types/type_factory.rb
lib/avromatic/model/types/union_type.rb

This PR improves coercion error messages by giving more context on the location of the coercion error. Here are some examples:
```
Could not coerce '1' to a String
Could not coerce '1' to string when setting Core::Events::DigitalAsset#url
Could not coerce '1' to a SalsifyUuid: Value is not a valid Salsify UUID: '1'
Could not coerce '1' to SalsifyUuid when setting Core::Events::Product#id
Could not coerce '"foobar"' to a SalsifyUuid: Value is not a valid Salsify UUID: 'foobar'
Could not coerce '["foobar"]' to array[SalsifyUuid] when setting ComputedProperty#formula_reference_property_ids
Could not coerce '{:id=>1}' to a union of ["Core::Events::Product", "Core::Events::DigitalAsset"]
Could not coerce '{:id=>1}' to union[Core::Events::Product, Core::Events::DigitalAsset] when setting …
```

Better coercion error messages

---

spec/avromatic/model/builder_spec.rb

This PR adds a test to verify that the union coercion algorithm selects the first union member type with all of the specified attribute values with the correct types.
Fixes #96

Additional test of union coercion algorithm

---

CHANGELOG.md
lib/avromatic/model/attributes.rb
spec/avromatic/model/builder_spec.rb

Now that the Virtus dependency has been removed we can call `super()` from the model constructor. This means we no longer have to play games with `prepend` and `inherited` callbacks in base event classes e.g.
```ruby
class AlertEvent
def self.inherited(subclass)
subclass.prepend(SalsifyAvro::MultitenantValue)
subclass.prepend(SalsifyAvro::UniquelyIdentifiableValue)
end
end
```
becomes
```ruby
class AlertEvent
include SalsifyAvro::MultitenantValue
include SalsifyAvro::UniquelyIdentifiableValue
end
```
@cgrdavies - you're prime
/cc @tjwp @jkapell

Call super() in model constructor

---

CHANGELOG.md
README.md

This beefs up the CHANGELOG a bit and removes the `Upgrading to 2.0` section from the README since the necessary content is covered in the CHANGELOG.

README Updates

---

lib/avromatic/model/types/abstract_timestamp_type.rb
lib/avromatic/model/types/timestamp_micros_type.rb
lib/avromatic/model/types/timestamp_millis_type.rb
spec/avromatic/model/builder_spec.rb
spec/spec_helper.rb

This PR fixes sporadic logical timestamp test failures like [this](https://travis-ci.org/salsify/avromatic/jobs/440805947) one. The problem was that [ActiveSupport::TimeWithZone](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/time_with_zone.rb#L479) overrides `is_a?` to make it look like a `Time` so the coercion algorithm wouldn't kick in if the test ran at time that happened to be on a millisecond boundary. This would lead to a test failure because `==` would return false for the actual `ActiveSupport::TimeWithZone` vs. the expected `Time`.

Fix sporadic logical timestamp test failures

---

README.md
lib/avromatic/model/attributes.rb
spec/avro/dsl/test/optional_boolean.rb
spec/avro/schema/test/optional_boolean.avsc
spec/avromatic/model/builder_spec.rb

This defines readers with the `?` suffix for boolean fields.

Define <attribute>? readers for booleans

---

lib/avromatic/model.rb
lib/avromatic/model/attributes.rb
lib/avromatic/model/types/abstract_timestamp_type.rb
lib/avromatic/model/types/abstract_type.rb
lib/avromatic/model/types/array_type.rb
lib/avromatic/model/types/boolean_type.rb
lib/avromatic/model/types/custom_type.rb
lib/avromatic/model/types/date_type.rb
lib/avromatic/model/types/enum_type.rb
lib/avromatic/model/types/fixed_type.rb
lib/avromatic/model/types/float_type.rb
lib/avromatic/model/types/integer_type.rb
lib/avromatic/model/types/map_type.rb
lib/avromatic/model/types/null_type.rb
lib/avromatic/model/types/record_type.rb
lib/avromatic/model/types/string_type.rb
lib/avromatic/model/types/union_type.rb
lib/avromatic/model/unknown_attribute_error.rb
spec/avromatic/model/builder_spec.rb

This PR improves type coercion errors by providing more details on the cause of the error. The test changes are the easiest way to see the updated error messages. It also fixes a bug that caused the unknown attribute detection code to generate an incorrect message for string attribute keys.
@skarger - you're prime

Improve type coercion errors

---

CHANGELOG.md
lib/avromatic/model/attributes.rb
lib/avromatic/model/builder.rb
lib/avromatic/model/field_helper.rb
lib/avromatic/version.rb
spec/avromatic/model/builder_spec.rb
spec/avromatic/model/messaging_serialization_spec.rb

This PR puts all generated model methods into a module so they can be overridden by subclasses (which Avromatic 1.0 supported).

Allow generated model attribute accessors to be overridden

---

CHANGELOG.md
lib/avromatic/model/types/timestamp_micros_type.rb
lib/avromatic/model/types/timestamp_millis_type.rb
spec/avromatic/model/builder_spec.rb
spec/spec_helper.rb

This fixes a bug where timestamp-millis where not coerced when the number of microseconds was divisible by 1,000 but the number of nanoseconds was not divisible by 1,000,000.
@skarger - you're prime

Fix timestamp-millis coercion

---

CHANGELOG.md
avromatic.gemspec
lib/avromatic/model/attributes.rb
lib/avromatic/version.rb

Instead of allocating two strings per attribute, we can cache this on the attribute definition.
Before:
```
Calculating -------------------------------------
avro   288.272k memsize (     0.000  retained)
2.392k objects (     0.000  retained)
50.000  strings (     0.000  retained)
Warming up --------------------------------------
avro    40.000  i/100ms
Calculating -------------------------------------
avro    415.694  (± 5.5%) i/s -      2.080k in   5.019321s
```
After:
```
Calculating -------------------------------------
avro   259.232k memsize (     0.000  retained)
1.666k objects (     0.000  retained)
50.000  strings (     0.000  retained)
Warming up --------------------------------------
avro    43.000  i/100ms
Calculating -------------------------------------
avro    446.097  (± …
```

Reduce string allocations during model initialization

---

CHANGELOG.md
lib/avromatic/model/message_decoder.rb
lib/avromatic/version.rb
spec/avromatic/model/message_decoder_spec.rb

This PR adds `key_schema_name` and `value_schema_name` attributes to `UnexpectedKeyError` so clients can perform more advanced error handling e.g. only log messages for unknown schemas once per schema/kafka topic.
@rlburkes - you're prime

Add structured information to UnexpectedKeyError

---

CHANGELOG.md
lib/avromatic/io/datum_reader.rb
lib/avromatic/version.rb

I recently hit a case where I was decoding over 4k Avromatic models within a single ruby process which caused the memory usage to bloat. After some investigation, I noticed that most of the memory usage was originating from this Avromatic gem and more specifically from `datum_reader.rb:13`. The `initial_record` is only used in one case in the method but the hash will be created for each call to `read_data`. The solution here is to use nil as the default value and only allocate the hash when we hit the intended case.
Test
For this benchmark, I decoded an example Avromatic model with several fields 1000 times with the following results:
1.906k (± 5.8%) i/s -      9.513k in   5.009166s
Total allocated: 78.82 MB (519000 objects)
Allocated by location
40.60 MB …

Avoid Allocating Empty Hash as Default Parameter

---

CHANGELOG.md
lib/avromatic.rb
lib/avromatic/model/nested_models.rb
lib/avromatic/model/types/abstract_type.rb
lib/avromatic/model/types/array_type.rb
lib/avromatic/model/types/boolean_type.rb
lib/avromatic/model/types/custom_type.rb
lib/avromatic/model/types/date_type.rb
lib/avromatic/model/types/enum_type.rb
lib/avromatic/model/types/fixed_type.rb
lib/avromatic/model/types/float_type.rb
lib/avromatic/model/types/integer_type.rb
lib/avromatic/model/types/map_type.rb
lib/avromatic/model/types/null_type.rb
lib/avromatic/model/types/record_type.rb
lib/avromatic/model/types/string_type.rb
lib/avromatic/model/types/timestamp_micros_type.rb
lib/avromatic/model/types/timestamp_millis_type.rb
lib/avromatic/model/types/union_type.rb
lib/avromatic/version.rb
spec/avro/dsl/test/nested_nested_record.rb
spec/avro/schema/test/nested_nested_record.avsc
spec/avromatic_spec.rb
spec/spec_helper.rb

Generated nested models register themselves upon being created by
`Avromatic::Model::Builder`. If Rails's autoloader didn't recreate a model that
should be eager loaded, then its nested models won't be registered as we hook on
Railtie `#to_prepare` that itself triggers a clean-up of the nested models
registry.
Therefore, we have to go through the attribute definitions of each eager loaded
model and try to register its nested models.
prime @jturkel

Load the nested models of eager loaded models

---

CHANGELOG.md
lib/avromatic/rspec.rb
lib/avromatic/version.rb
spec/spec_helper.rb

This adds support for stubbing schema registry URLs with usernames and passwords. Previously the stubbing wouldn't work because the WebMock URL regex was incorrectly including the username/password.

Fake schema registry support for URLs with authentication

---

CHANGELOG.md
lib/avromatic/io/datum_reader.rb
lib/avromatic/model/attributes.rb
lib/avromatic/model/raw_serialization.rb
lib/avromatic/model/types/abstract_timestamp_type.rb
lib/avromatic/model/types/abstract_type.rb
lib/avromatic/model/types/array_type.rb
lib/avromatic/model/types/boolean_type.rb
lib/avromatic/model/types/custom_type.rb
lib/avromatic/model/types/date_type.rb
lib/avromatic/model/types/enum_type.rb
lib/avromatic/model/types/fixed_type.rb
lib/avromatic/model/types/float_type.rb
lib/avromatic/model/types/integer_type.rb
lib/avromatic/model/types/map_type.rb
lib/avromatic/model/types/null_type.rb
lib/avromatic/model/types/record_type.rb
lib/avromatic/model/types/string_type.rb
lib/avromatic/model/types/union_type.rb
lib/avromatic/version.rb

This PR is part of a series of memory optimizations to our Avro related libraries that reduce serialization memory consumption by 62% and deserialization memory consumption 43% for some of our complex models
A few more details on the optimizations:
* `Avromatic::Model::RawSerialization::Encode#avro_hash` was doing two unnecessary hash allocations
* `Avromatic::Model::Attributes#initialize` was allocating an unnecessary array and hash for each defaulted attribute
* Passing `strict` as a positional argument rather than a keyword argument in `Avromatic::Model::Types::*Type#serialize` avoids a hash allocation on a very hot codepath
* `Avromatic::IO::DatumReader#read_data` was allocating an unnecessary hash for each "optional", non-record attribute value
@will89 - you're prime
/cc @kphelps

Memory optimizations

---

CHANGELOG.md
lib/avromatic/model/configurable.rb
lib/avromatic/model/raw_serialization.rb
lib/avromatic/version.rb

7% of the memory allocated by our Avromatic serialization benchmarks comes from converting symbolized field names (the format used internally by Avromatic) to string field names (the format used by Avro). Fortunately this information is very cacheable at the model class level :) This optimization improves memory allocation but the throughput improvements are in the margin of error.
@will89 - you're prime

Serialization memory optimizations

---

lib/avromatic.rb
lib/avromatic/model/builder.rb
lib/avromatic/native/stubs.rb
spec/avromatic/model/builder_spec.rb
spec/avromatic/model/builder_validation_spec.rb
src/descriptors.rs
src/macros.rs
src/model.rs

@kphelps prime, because I'm not sure how crazy this approach is. Essentially I'm trying to stub enough data over to the existing mixins for them to do the validation logic as they do today. This fixes something like 8 test cases. Validations around nested objects and unions are still failing, but I think we have issues with nesting and unions in general in the class builder.

[Native] Allow some validations to work.

---

CHANGELOG.md
lib/avromatic/model/attributes.rb
lib/avromatic/model/configurable.rb
lib/avromatic/model/configuration.rb
lib/avromatic/model/raw_serialization.rb
lib/avromatic/model/validation.rb
lib/avromatic/version.rb
spec/avromatic/model/builder_spec.rb
spec/avromatic/model/raw_serialization_spec.rb

This PR fixes a bug where Avromatic was incorrectly caching validation results and serialized attributes when an immutable model had mutable children. I noticed this while working on #131.
/cc @askreet

Fix immutable caching

---

CHANGELOG.md
lib/avromatic/model/nested_models.rb
lib/avromatic/model_registry.rb
lib/avromatic/version.rb
spec/avromatic/model/builder_nested_models_spec.rb
spec/avromatic/model_registry_spec.rb

This PR fixes a regression introduced by #119 that caused Avromatic to not detect models that conflict with already generated models due to improper eager loading configuration. This bug lead to hard to troubleshoot downstream errors like this when instantiating model instances:
```
Avromatic::Model::CoercionError: Value for TargetSchemas::Events::ApplicableScope#field_conditions could not be coerced to a array[FieldCondition]. Provided argument: [#<TargetSchemas::Events::FieldCondition field: #<Core::Events::Reference id: SalsifyUuid('s-8073254e-9d10-487f-8749-a44d04519f1b'), type: "target_schema_fields", external_id: "Field 000000000 ID">, values: ["foo", "bar"], operator: nil, quantifier: nil>]
```
With this bug fix we now get a more actionable error message at model definition time: …

Detect already registered nested models

---

CHANGELOG.md
README.md
lib/avromatic.rb
lib/avromatic/rspec.rb
lib/avromatic/version.rb

This PR updates the RSpec integration to clear schema registry caches are cleared between tests which ensures consistent ID mappings with the `AvroSchemaRegistry::FakeServer`. As part of this fix I added an `Avromatic.build_schema_registry!` method for consistency with the existing `Avromatic.build_messaging!` method.

Ensure schema registry caches are cleared between tests

---

CHANGELOG.md
README.md
lib/avromatic/model/configurable.rb
lib/avromatic/model/configuration.rb
lib/avromatic/model/messaging_serialization.rb
lib/avromatic/version.rb
spec/avromatic/model/builder_spec.rb
spec/avromatic/model/messaging_serialization_spec.rb

This is an attempt to address https://github.com/salsify/avromatic/issues/141. It seems like some tools like ksqlDB have schema naming conventions that are not allowed within the avro naming conventions. ksqlDB expects all schemas to be ending in a `-value` in the schema registry, https://docs.ksqldb.io/en/latest/operate-and-deploy/schema-registry-integration/.
prime: @jturkel

Add support for specifying a subject for the avro schema when building an Avromatic model

---

CHANGELOG.md
avromatic.gemspec

While debugging I noticed this gem was including several irrelevant files including `.circleci/`, `.github/`, `gemfiles/`, and `log/`. This PR switches to only including the relevant files.
@sgh304 - you're prime

Remove extraneous files from gem distribution

---

README.md

This PR updates the README to make it a little clearer when configuring a schema registry that you have the option to either provide an instance of a compatible registry object or just specify the registry_url. `build_schema_registry` uses the registry_url to instantiate an instance of a compatible registry class.
Setting schema_registry and a registry_url, followed by a call to build_schema_registry will override whatever was passed in as the value of schema_registry with the instantiation of the ConfluentSchemaRegistry instance configured with the registry_url.
This also updates the example to show that `build_messaging` will call `build_schema_registry`. That both do not need to be called explicitly (at least when providing registry_url).

Updates readme to make it a little clearer when configuring a schema registry

---

CHANGELOG.md
README.md
lib/avromatic.rb
lib/avromatic/model/types/decimal_type.rb
lib/avromatic/model/types/type_factory.rb
spec/avro/dsl/test/logical_types.rb
spec/avro/schema/test/logical_types.avsc
spec/avro/schema/test/logical_types_with_decimal.avsc
spec/avromatic/model/builder_spec.rb
spec/support/contexts/logical_types_serialization.rb

It adds support for the decimal logical type, so the following Avro schema can be processed correctly:
```json
{
"type": "bytes",
"logicalType": "decimal",
"precision": 4,
"scale": 2
}
```
However, It's only supported by the Avro v1.11.x. If that's ok, I'm open for suggestions how to better restrict that feature to supported avro version.
https://avro.apache.org/docs/1.11.1/specification/#decimal

Add support for decimal logical type

---

lib/avromatic/version.rb

Trigger a release of 4.3.0 which includes support for the decimal logical type introduced in https://github.com/salsify/avromatic/pull/151.
@gremerritt - you're prime

Release 4.3.0

---

CHANGELOG.md
lib/avromatic/version.rb

Release 5.1.0 which includes the support for Rails 7.2 included in #164.

Release 5.1.0

---

CHANGELOG.md
lib/avromatic/model/types/union_type.rb
lib/avromatic/version.rb
spec/avro/dsl/test/real_int_union.rb
spec/avro/schema/test/real_int_union.avsc
spec/avromatic/io/datum_writer_spec.rb

#166 introduced a bug writing a non-big int to a union that only has `long` as the supported int type.
> Expected 1 to be one of ["String", "Integer"]
This PR fixes the bug by also looking for a `BigIntType` member type.
prime: @jturkel 
[PIMCORE-2190]
[PIMCORE-2190]: https://salsify.atlassian.net/browse/PIMCORE-2190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PIMCORE-2190] Fix writing non-big ints to `long` unions
