- CHANGELOG.md
- avromatic.gemspec
- lib/avromatic/model/decoder.rb
- lib/avromatic/version.rb
> Remove dependency on private_attr

- .rubocop.yml
- CHANGELOG.md
- Gemfile
- avromatic.gemspec
- lib/avromatic/model/attributes.rb
- lib/avromatic/version.rb
This required some actual changes based on the monkey-patched handling for false defaults in schemas.
I also update to the latest shared rubocop configuration.
> Update to avro_turf v0.7.0

- CHANGELOG.md
- lib/avromatic/model/raw_serialization.rb
- lib/avromatic/version.rb
> Remove dependency on transform_values from ActiveSupport v4.2

- .gitignore
- .travis.yml
- gemfiles/rails4_1.gemfile
- gemfiles/rails4_2.gemfile
Start by adding configurations for ruby and Rails versions that Salsify if using.
> Add test configurations for different ActiveModel/ActiveSupport versions

- README.md
A couple of things had fallen behind with nested models and validation.
> Some README cleanup

- CHANGELOG.md
- lib/avromatic.rb
- lib/avromatic/model_registry.rb
- lib/avromatic/railtie.rb
- lib/avromatic/version.rb
- spec/spec_helper.rb
Let me know if you want me to cut a pre-release with this. I'll update the README as a follow-up task. 
> Add hooks to preload models and handle Rails reload

- CHANGELOG.md
- README.md
- lib/avromatic/version.rb
> Add on_initialize to the README

- avromatic.gemspec
- spec/avromatic/model/builder_nested_models_spec.rb
- spec/avromatic/model/builder_spec.rb
- spec/avromatic/model/builder_validation_spec.rb
- spec/avromatic/model/message_decoder_spec.rb
- spec/avromatic/model_registry_spec.rb
- spec/avromatic_spec.rb
A few corrections from RSpec cops.
> Update to salsify_rubocop v0.45

- .travis.yml
> Test against newer rubies

- CHANGELOG.md
- README.md
- lib/avromatic.rb
- lib/avromatic/schema_registry_patch.rb
- lib/avromatic/version.rb
- spec/avromatic/schema_registry_patch_spec.rb
> Add use_cacheable_schema_registration configuration

- CHANGELOG.md
- lib/avromatic/io/datum_reader.rb
- lib/avromatic/version.rb
- spec/avromatic/io/datum_reader_spec.rb
Added some test coverage to demonstrate that correct errors are now raised.
Prime: @mattcross
> Namespace Avro errors in Avromatic::IO::DatumReader

- CHANGELOG.md
- README.md
- avromatic.gemspec
- lib/avromatic.rb
- lib/avromatic/model/message_decoder.rb
- lib/avromatic/rspec.rb
- lib/avromatic/schema_registry_patch.rb
- lib/avromatic/test/fake_confluent_schema_registry_server.rb
- lib/avromatic/test/fake_schema_registry_server.rb
- lib/avromatic/version.rb
- spec/avromatic/schema_registry_patch_spec.rb
- spec/avromatic_spec.rb
> Compatibility with avro_turf v0.8.0

- CHANGELOG.md
- lib/avromatic.rb
- lib/avromatic/version.rb
> Add support for schema store with a clear_schemas method

- CHANGELOG.md
- lib/avromatic/schema_registry_patch.rb
- lib/avromatic/version.rb
- spec/avromatic/schema_registry_patch_spec.rb
> Support additional params in compatibility check

- avromatic.gemspec
- spec/avromatic/model/builder_spec.rb
> Update to salsify_rubocop v0.48.0

- CHANGELOG.md
- README.md
- lib/avromatic/model/builder.rb
- lib/avromatic/model/configuration.rb
- lib/avromatic/version.rb
- spec/avromatic/model/builder_spec.rb
> Add mutable option

- CHANGELOG.md
- README.md
- lib/avromatic/model/attributes.rb
- lib/avromatic/model/configuration.rb
- lib/avromatic/version.rb
- spec/avro/dsl/test/key_with_optional.rb
- spec/avro/schema/test/key_with_optional.avsc
- spec/avromatic/model/builder_spec.rb
> Prevent optional fields in key schemas

- CHANGELOG.md
- lib/avromatic.rb
- lib/avromatic/model/raw_serialization.rb
- lib/avromatic/patches.rb
- lib/avromatic/patches/schema_validator_patch.rb
- lib/avromatic/version.rb
- spec/avro/dsl/test/optional_array.rb
- spec/avro/dsl/test/optional_record.rb
- spec/avro/schema/test/optional_array.avsc
- spec/avro/schema/test/optional_record.avsc
- spec/avromatic/model/messaging_serialization_spec.rb
> Fix caching of optional fields

- lib/avromatic/model_registry.rb
- spec/avromatic/model_registry_spec.rb
> Fix model registration

- CHANGELOG.md
- lib/avromatic/model/types/timestamp_micros_type.rb
- lib/avromatic/model/types/timestamp_millis_type.rb
- lib/avromatic/version.rb
- spec/avro/dsl/test/nested_nested_record.rb
- spec/avro/schema/test/nested_nested_record.avsc
> Fix method #referenced_model_classes declaration

- .github/CODEOWNERS
- avromatic.gemspec
> Add CODEOWNERS and update gemspec

- README.md
Part 1 of the changes decided on in https://github.com/salsify/salsify_avro/pull/66
Note: Some of the info existed here so only added what felt necessary.
https://salsify.atlassian.net/browse/ALYS-6448
prime: @jturkel 
cc: @salsify/analytics
> [ALYS-6448] Update Avro documentation

- .circleci/config.yml
- Appraisals
- avromatic.gemspec
- gemfiles/avro1_11_rails7_2.gemfile
Not sure if you’d prefer to open-end the version check here or use `< 8`.
> Add support for Rails 7.2

- CHANGELOG.md
- lib/avromatic/version.rb
This releases a new version with the changes from https://github.com/salsify/avromatic/pull/166.
prime: @jturkel
> Release 5.1.1
